#ifndef VERSION_H
#define VERSION_H

#define STRINGIZE2(s) #s
#define STRINGIZE(s) STRINGIZE2(s)

#define VERSION_MAJOR 2
#define VERSION_MINOR 0
#define VERSION_PATCH 0
#define VERSION_PRERELEASE rc
#define VERSION_APPLICATION "v" STRINGIZE(VERSION_MAJOR) "." STRINGIZE(VERSION_MINOR) "." STRINGIZE(VERSION_PATCH) "_" STRINGIZE(VERSION_PRERELEASE)

#endif // VERSION_H
